services:
  db:
    image: postgres:16-alpine
    container_name: poker-db
    restart: always
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d poker"]
      interval: 5s
      timeout: 5s
      retries: 10

  app-backend:
    build:
      context: ../app-backend
    container_name: app-backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/poker?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      MINI_APP_URL: ${MINI_APP_URL}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app-backend

volumes:
  db_data:



#services:
#  db:
#    image: postgres:16-alpine
#    container_name: poker-db
#    environment:
#      POSTGRES_DB: poker
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d poker"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  app-backend:
#    build:
#      context: ../app-backend
#    container_name: app-backend
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db:5432/poker?sslmode=disable
#      JWT_SECRET: supersecret
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#
##  clock-backend:
##    build:
##      context: ../clock-backend
##    container_name: clock-backend
##    environment:
##      DATABASE_URL: postgres://postgres:postgres@db:5432/poker?sslmode=disable
##    depends_on:
##      db:
##        condition: service_healthy
##    ports:
##      - "8081:8081"
#
#volumes:
#  db_data: