services:
  db:
    image: postgres:16-alpine
    container_name: poker-db
    restart: always
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d poker"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app-backend:
    build:
      context: ../app-backend
    container_name: app-backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/poker?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      MINI_APP_URL: ${MINI_APP_URL}
      PORT: ${PORT}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    networks:
          - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  telegram-bot:
    build:
      context: ../telegram-bot
    container_name: telegram-bot
    restart: always
    environment:
     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
     API_BASE_URL: http://app-backend:8080/api
     MINI_APP_URL: ${MINI_APP_URL}
    depends_on:
      - app-backend
    networks:
      - app-network
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app-backend
    networks:
      - app-network

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge

#services:
#  db:
#    image: postgres:16-alpine
#    container_name: poker-db
#    environment:
#      POSTGRES_DB: poker
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d poker"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  app-backend:
#    build:
#      context: ../app-backend
#    container_name: app-backend
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db:5432/poker?sslmode=disable
#      JWT_SECRET: supersecret
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#
##  clock-backend:
##    build:
##      context: ../clock-backend
##    container_name: clock-backend
##    environment:
##      DATABASE_URL: postgres://postgres:postgres@db:5432/poker?sslmode=disable
##    depends_on:
##      db:
##        condition: service_healthy
##    ports:
##      - "8081:8081"
#
#volumes:
#  db_data:

 # scp -f /Users/assistentka_professora/Desktop/poker-clock/telegram-bot root@85.239.63.25:/backend